spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: '00000000'
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rule?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC


mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml